version: '3'

services:

  postgresql:
    container_name: postgresql
    hostname: postgresql
    privileged: true
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db_init/init.sh:/docker-entrypoint-initdb.d/init.sh"

networks:
  backend:
    driver: "bridge"

volumes:
  dbdata:
